### ISSUE TITLE
The Ansible module should be in a dedicated repository

### ISSUE THREAD

**Issue by Malizor** [Zempashi/stratus#15]
Hi,

Thank you for this wonderful project.

"stratus_vm.py" should live in a dedicated repository, so that it can be included in other projects via ansible galaxy or git submodules.

Currently we have to duplicate the file between projects, which is not practical at all.

What do you think?

**Comment by Zempashi** [comment]
Ansible-galaxy doesn't clone with recursive option. So it doesn't work with ansible-galaxy. I hasn't in mind the git submodule. That's seems a good argument to move the submodule.
I believe that you whant to make the submodule to be called 'library', so I'll put the submodule on the root

**Comment by Malizor** [comment]
Great!
And in case we want to have multiple libraries, we can just include it elsewhere and do a symlink.

**Comment by Zempashi** [comment]
https://github.com/Zempashi/stratus_ansible_module. And voilà ^^

**Comment by Malizor** [comment]
You are the best!
Of course it might be better to have some kind of documentation about the module in its repository, but this can be seen later.

**Comment by Zempashi** [comment]
Other ansible module self contains there doc. There is job at ansible inc. that generate doc from modules.
I think self containing doc is a good thing (versionned in the git as well as the code), but doesn't look very well in the code itself...I don't know if the doc generation is open source
